channels:
- uibcdf
- conda-forge
- ambermd
- defaults
dependencies:
- python
- pip
- setuptools >=61.0
- versioningit~=2.0
- h5py
- numpy
- numba
- pyunitwizard
- mmtf-python
- pandas
- jinja2
- openmm
- pdbfixer
- nglview
- ambertools
- networkx
- mdtraj
- mdanalysis
- biopython
- ipywidgets
- tqdm
- pip:
  - mmcif
