package:
  name: bcifreader
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  run:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  - future
  - six
  - requests
  - msgpack-python
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'XXX

    '
  dev_url: https://github.com/uibcdf/bcifreader
  doc_url: https://uibcdf.org/bcifreader
